- name: Installing Java
  shell : sudo amazon-linux-extras install java-openjdk11 -y

- name: adding repo
  shell: sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo

- name: adding key
  shell: sudo rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: adding key
  shell: sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: adding key
  shell: sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

- name: Install jenkins server
  yum: name=jenkins state=latest
  notify: Restart jenkins
